language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

matrix:
  include:
  - python: '3.7'
    dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
    sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq pandoc

install:
- pip install -r requirements.txt -r test-requirements.txt
- pip install .

script: ./build.sh

after_success: coveralls

deploy:
  - provider: pypi
    user: odi
    password:
      secure: "EfW0Fje7pn/iLv2+eiFGc/PwD2jcdfF5Df9uUKWTCRP8wqMrFriErTczlWqfEIARZDnxQXU5c+UWEQvZ/5D5/4ZctJyvMcmgYi7I1ECXVwYQh0c5prsFl+9uynNJQWfW404v5Kb3MJE1iGaSEOeonObeqThQGdtDTPYZd9H4j20="
    on:
      tags: true
      all_branches: true
      python: 3.7
      repo: metaodi/osmapi
